name: Coffee News Automator

on:
  schedule:
    # 月〜土曜 日本時間の朝8:00 (UTCの23:00)
    - cron: '0 23 * * 1-6'
    # 日曜 日本時間の朝8:00 (UTCの23:00)
    - cron: '0 23 * * 0'
  workflow_dispatch:
    inputs:
      type:
        description: 'ニュースの種類 (daily / weekly)'
        required: true
        default: 'daily'
        type: choice
        options:
          - daily
          - weekly

jobs:
  run-daily-news:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのコードを取得
        uses: actions/checkout@v4

      - name: Python環境のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: 必要なパッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 【Daily】今日のコーヒーニュースを実行 (月〜土)
        if: github.event.schedule == '0 23 * * 1-6' || inputs.type == 'daily'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          GMAIL_TOKEN_B64: ${{ secrets.GMAIL_TOKEN_B64 }}
          GMAIL_CREDENTIALS_B64: ${{ secrets.GMAIL_CREDENTIALS_B64 }}
        run: |
          # Base64で保存した認証情報をファイルに戻す
          echo "$GMAIL_TOKEN_B64" | base64 --decode > token.json
          echo "$GMAIL_CREDENTIALS_B64" | base64 --decode > credentials.json
          python main.py

      - name: 【Weekly】今週のコーヒーニュースまとめを実行 (日曜日のみ)
        if: github.event.schedule == '0 23 * * 0' || inputs.type == 'weekly'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          GMAIL_TOKEN_B64: ${{ secrets.GMAIL_TOKEN_B64 }}
          GMAIL_CREDENTIALS_B64: ${{ secrets.GMAIL_CREDENTIALS_B64 }}
        run: |
          echo "$GMAIL_CREDENTIALS_B64" | base64 --decode > credentials.json
          python main.py --weekly

      - name: 生成されたデータの公開 (GitHub Pagesへ)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true # Keep old files if any exist
          commit_message: "Deploy latest news data"
